#!/bin/sh
# zrep-init
# zrep/ksh9x add-on for NAS4Free/XigmaNAS Embedded x64 11.x and later.
# (https://www.xigmanas.com/forums/viewtopic.php?f=71&t=13966)
# Credits: Philip Brown (pbrown) ZREP: http://www.bolthole.com/solaris/zrep/
# License: BSD2CLAUSE (BSD 2-clause Simplified License).
# Debug script
#set -x

# Copyright (c) 2018 José Rivera (JoseMR)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS 'AS IS' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Set environment.
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

# Determine full working directory.
CWDIR=$(dirname $(realpath $0))

# Global variables.
PLATFORM=$(uname -m)
PRODUCT=$(uname -i)
PRDVERSION=$(uname -r | cut -d '-' -f1 | tr -d '.')
PRDPLATFORM=$(cat /etc/platform)
SCRIPTNAME=$(basename $0)
CONFIG="/cf/conf/config.xml"
APPNAME="zrep"
KSH9X="ksh93"
EXTLOGFILE="${CWDIR}/log/zrep_ext.log"
ZREPLOGFILE=${EXTLOGFILE}
FULLAPPNAME="${APPNAME}-addon"
PKGCONF="/etc/pkg/FreeBSD.conf"
PKGCACHE="/var/cache/pkg"
USRLOCAL="/usr/local"
KSH9PATH="${USRLOCAL}/bin"
ZREPPATH="${USRLOCAL}/bin"
LOCALSHAREPATH="${USRLOCAL}/share"
WWWPATH="/usr/local/www"
ZREPCONF="/conf/zrep_config"
ZREPCONFLINK="/var/etc/zrepconf"
INSTALLPATH="${CWDIR}/${FULLAPPNAME}"
BRANCH="master"
ZREPURL="https://github.com/bolthole/${APPNAME}/archive/${BRANCH}.zip" # Includes latest bugfixes and portability.
ZREP_VERSION="https://raw.githubusercontent.com/bolthole/${APPNAME}/${BRANCH}/zrep"
GITURL="https://github.com/JRGTH/xigmanas-${APPNAME}-extension/archive/${BRANCH}.zip"
VERFILE="https://raw.githubusercontent.com/JRGTH/xigmanas-${APPNAME}-extension/${BRANCH}/version"

error_notify()
{
	# Log/notify message on error and exit.
	MSG="$*"
	logger -t "${SCRIPTNAME}" "${MSG}"
	echo -e "$*" >&2; exit 1
}

runtime_config()
{
	# Create required directories if missing.
	if [ ! -d ${CWDIR}/conf ]; then
		mkdir -p ${CWDIR}/conf
	fi
	if [ ! -d ${CWDIR}/log ]; then
		mkdir -p ${CWDIR}/log
	fi
	if [ ! -d ${CWDIR}/locale-zrep ]; then
		mkdir -p ${CWDIR}/locale-zrep
	fi
}

update_freebsdconf()
{
	# Update FreeBSD.conf to fetch latest packages.
	if [ -f ${PKGCONF} ]; then 
		if grep -q "quarterly" ${PKGCONF}; then
			sed -i '' -E "s/quarterly/latest/g" ${PKGCONF} || \
			error_notify "Error: A problem has occurred while updating FreeBSD.conf file."
		fi
	fi
}

ksh9x_native_download()
{
	# Install latest ksh9x package.
	if ! pkg info | grep -q ${KSH9X}; then
		# Check if ksh9x already exist.
		if [ ! -f ${KSH9PATH}/${KSH9X} ]; then
			update_freebsdconf
			pkg install -y ${KSH9X} || error_notify "Error: A problem has occurred while fetching ${KSH9X}."
		fi
	fi
}

ksh9x_initial_download()
{
	# Check if ksh9x already exist.
	if [ ! -f ${CWDIR}/${FULLAPPNAME}/${KSH9PATH}/${KSH9X} ]; then
		# Fetch ksh9x package.
		update_freebsdconf
		pkg fetch -y -o ${CWDIR}/download ${KSH9X} || \
		error_notify "Error: A problem has occurred while fetching ${KSH9X}."
		ksh9x_pkg_extract
	fi
}

ksh9x_pkg_extract()
{
	# Extract fetched package for Embedded platform.
	if [ ! -f ${CWDIR}/${FULLAPPNAME}/${KSH9X}/+MANIFEST ]; then
		echo "Extracting ${KSH9X}..."
		tar -Jxf ${CWDIR}/download/All/${KSH9X}-*.txz -C ${CWDIR}/${FULLAPPNAME}/ || \
		error_notify "Error: A problem has occurred while extractig ${KSH9X} files."
		mkdir -p ${CWDIR}/${FULLAPPNAME}/${KSH9X}
		mv ${CWDIR}/${FULLAPPNAME}/+* ${CWDIR}/${FULLAPPNAME}/${KSH9X}
		rm ${CWDIR}/download/All/${KSH9X}-*.txz
		echo "Done!"
	fi
}

zrep_initial_download()
{
	# Check if zrep already exist.
	if [ ! -f ${CWDIR}/${FULLAPPNAME}/${ZREPPATH}/${APPNAME} ]; then
		# Fetch latest zrep package.
		echo "Fetching ${APPNAME} files..."
		fetch -ao ${CWDIR}/${BRANCH}.zip --no-verify-peer --timeout=30 ${ZREPURL} || \
		error_notify "Error: A problem has occurred while fetching ${APPNAME}."
		zrep_pkg_extract
	fi
}

zrep_upgrade()
{
	# Perform an online zrep upgrade.
	DATE=$(date +"%a %b %d %T %Y")
	echo "Looking for new ${APPNAME} package!"
	mkdir -p ${CWDIR}/update
	fetch -ao ${CWDIR}/update --no-verify-peer --timeout=30 ${ZREP_VERSION} || \
	error_notify "Error: A problem has occurred while fetching version file."

	# Compare version files and fetch latest package if available.
	if [ -f ${CWDIR}/update/${APPNAME} ]; then
		UPDATEVER=$(cat ${CWDIR}/update/${APPNAME} | grep ZREP_VERSION= | egrep -o "([0-9]{1,}\.)+[0-9]{1,}" | tr -d '.')
		CURRENTVER=$(cat ${ZREPPATH}/${APPNAME} | grep ZREP_VERSION= | egrep -o "([0-9]{1,}\.)+[0-9]{1,}" | tr -d '.')
		if [ "${UPDATEVER}" -gt "${CURRENTVER}" ]; then
			echo "New ${APPNAME} package found, performing upgrade..."
			fetch -ao ${CWDIR}/update --no-verify-peer --timeout=30 ${ZREPURL} || \
			error_notify "Error: A problem has occurred while fetching ${APPNAME} package."
			tar -xf ${CWDIR}/update/${BRANCH}.zip --exclude='.git*' -C ${CWDIR}/update --strip-components 1 zrep-master/zrep
			rm -f ${CWDIR}/update/${BRANCH}.zip
			chmod 555 ${CWDIR}/update/${APPNAME}
			cp -Rf ${CWDIR}/update/* ${CWDIR}/${FULLAPPNAME}/${ZREPPATH}/${APPNAME}
			rm -R ${CWDIR}/update
			update_zrep_shebang

			# Logging the update event.
			UPDATEVERSION=$(cat ${ZREPPATH}/${APPNAME} | grep ZREP_VERSION= | cut -d"=" -f2)
			echo "${DATE}: ${APPNAME} upgraded to ${UPDATEVERSION}" >> ${EXTLOGFILE}
			echo "${APPNAME} upgraded to version ${UPDATEVERSION}"
			echo "${APPNAME} package upgrade completed!"
		else
			echo "${APPNAME} is on the latest version!"
			rm -R ${CWDIR}/update
		fi
	fi
}

zrep_pkg_extract()
{
	# Extract zrep script from package.
	if [ -f ${CWDIR}/master.zip ]; then
		if [ ! -f ${CWDIR}/${FULLAPPNAME}${ZREPPATH}/${APPNAME} ]; then
			echo "Extracting ${APPNAME}..."
			tar -xf ${CWDIR}/${BRANCH}.zip -C ${CWDIR}/${FULLAPPNAME}${ZREPPATH} --strip-components 1 zrep-master/zrep || \
			error_notify "Error: A problem has occurred while extractig ${APPNAME} files."
			chmod 555 ${CWDIR}/${FULLAPPNAME}${ZREPPATH}/${APPNAME}
			rm -f ${CWDIR}/${BRANCH}.zip
			update_zrep_shebang
			echo "Done!"
		fi
	fi
}

update_zrep_shebang()
{
	# Update zrep shebang to meet FreeBSD requirements.
	if [ -f ${CWDIR}/${FULLAPPNAME}${ZREPPATH}/${APPNAME} ]; then 
		if grep -q "#!/bin/ksh" ${CWDIR}/${FULLAPPNAME}${ZREPPATH}/${APPNAME}; then
			sed -i '' '1s/.*/#!\/usr\/local\/bin\/ksh93\ -p/' ${CWDIR}/${FULLAPPNAME}${ZREPPATH}/${APPNAME} || \
			error_notify "Error: A problem has occurred while updating zrep shebang."
		fi
	fi
}

ext_initial_download()
{
	# Always ensure the version file is present, otherwise update the extension files on startup.
	if [ ! -f ${CWDIR}/version ]; then
		echo "Fetching and extracting extension files..."
		mkdir -p ${CWDIR}/update
		fetch -ao ${CWDIR}/update --no-verify-peer --timeout=30 ${GITURL} || \
		error_notify "Error: A problem has occurred while fetching extension package."
		tar -xf ${CWDIR}/update/${BRANCH}.zip --exclude='.git*' --strip-components 1 -C ${CWDIR}/update
		chmod +x ${CWDIR}/update/${SCRIPTNAME}
		cp -Rf ${CWDIR}/update/* ${CWDIR}/
		rm -R ${CWDIR}/update
		echo "Done!"
	fi
}

extension_upgrade()
{
	# Perform an online extension upgrade.
	DATE=$(date +"%a %b %d %T %Y")
	echo "Looking for new extension package!"
	mkdir -p ${CWDIR}/update
	fetch -ao ${CWDIR}/update --no-verify-peer --timeout=30 ${VERFILE} || \
	error_notify "Error: A problem has occurred while fetching version file."

	# Compare version files and fetch latest package if available.
	if [ -f ${CWDIR}/update/version ]; then
		UPDATEVER=$(cat ${CWDIR}/update/version | tr -d .)
		CURRENTVER=$(cat ${CWDIR}/version | tr -d .)
		if [ "${UPDATEVER}" -gt "${CURRENTVER}" ]; then
			echo "New ${FULLAPPNAME} package found, performing upgrade..."
			fetch -ao ${CWDIR}/update --no-verify-peer --timeout=30 ${GITURL} || \
			error_notify "Error: A problem has occurred while fetching extension package."
			tar -xf ${CWDIR}/update/${BRANCH}.zip --exclude='.git*' --strip-components 1 -C ${CWDIR}/update
			chmod +x ${CWDIR}/update/${SCRIPTNAME}
			rm -f ${CWDIR}/update/${BRANCH}.zip
			cp -Rf ${CWDIR}/update/* ${CWDIR}/
			rm -R ${CWDIR}/update

			# Logging the update event.
			UPDATEVERSION=$(cat ${CWDIR}/version)
			echo "${DATE}: extension upgraded to ${UPDATEVERSION}" >> ${EXTLOGFILE}
			echo "Extension package upgrade completed!"
		else
			echo "Extension package is on the latest version!"
			rm -R ${CWDIR}/update
		fi
	fi
}

product_check()
{
	# Check for the working product.
	if [ "${PRODUCT}" = "NAS4FREE-x64" ] || [ "${PRODUCT}" = "XIGMANAS-x64" ]; then
		postinit_cmd
		gui_start
	fi
}

create_addon_env()
{
	# Create required directories.
	if [ ! -d ${CWDIR}/conf ]; then
		mkdir -p ${CWDIR}/conf
	fi
	if [ ! -d ${CWDIR}/locale-zrep ]; then
		mkdir -p ${CWDIR}/locale-zrep
	fi
	if [ ! -d ${CWDIR}/download/All ]; then
		mkdir -p ${CWDIR}/download/All
	fi
	if [ ! -d ${CWDIR}/log ]; then
		mkdir -p ${CWDIR}/log
	fi
	if [ ! -d ${CWDIR}/${FULLAPPNAME} ]; then
		mkdir -p ${CWDIR}/${FULLAPPNAME}
	fi
	if [ ! -d ${CWDIR}/${FULLAPPNAME}/${ZREPPATH} ]; then
		mkdir -p ${CWDIR}/${FULLAPPNAME}/${ZREPPATH}
	fi

	# Link zrep-init to /usr/local/sbin.
	if [ ! -f ${USRLOCAL}/sbin/${SCRIPTNAME} ]; then
		ln -fs ${CWDIR}/${SCRIPTNAME} ${USRLOCAL}/sbin/${SCRIPTNAME}
	fi
}

platform_check()
{
	# Check for working platform.
	if [ "${PRDPLATFORM}" = "x64-embedded" ]; then
		create_addon_env
		ext_initial_download
		ksh9x_initial_download
		zrep_initial_download
		sys_symlinkdir
	elif [ "${PRDPLATFORM}" = "x64-full" ]; then
		create_addon_env
		ext_initial_download
		ksh9x_native_download
		zrep_initial_download
		bin_symlinks
	fi
}

bin_symlinks()
{
	# Main zrep/ksh9x symlinks.
	if [ -d ${INSTALLPATH}/${USRLOCAL}/bin ]; then
		cd ${INSTALLPATH}/${USRLOCAL}/bin
		for file in *
			do
				ln -Ffhs ${INSTALLPATH}/${USRLOCAL}/bin/${file} ${USRLOCAL}/bin/${file}
		done
	fi
}

sys_symlinkdir()
{
	# Check and create/relink required symlinks/dirs for zrep/ksh9x.
	# This environment will be checked each time the script is started for consistency.

	# Required directories for ksh9x.
	if [ ! -d ${USRLOCAL}/share/examples ]; then
		mkdir -p ${USRLOCAL}/share/examples
	fi
	if [ ! -d ${USRLOCAL}/man/man1 ]; then
		mkdir -p ${USRLOCAL}/man/man1
	fi
	if [ ! -d ${USRLOCAL}/share/licenses ]; then
		mkdir -p ${USRLOCAL}/share/licenses
	fi

	bin_symlinks

	# Required symlinks for ksh9x. 
	if [ -d ${INSTALLPATH}/${USRLOCAL}/man/man1 ]; then
		cd ${INSTALLPATH}/${USRLOCAL}/man/man1
		for file in *
			do
				ln -Ffhs ${INSTALLPATH}/${USRLOCAL}/man/man1/${file} ${USRLOCAL}/man/man1/${file}
		done
	fi
	if [ -d ${INSTALLPATH}/${USRLOCAL}/share/examples ]; then
		cd ${INSTALLPATH}/${USRLOCAL}/share/examples
		for file in *
			do
				ln -Ffhs ${INSTALLPATH}/${USRLOCAL}/share/examples/${file} ${USRLOCAL}/share/examples/${file}
		done
	fi
	if [ -d ${INSTALLPATH}/${USRLOCAL}/share/licenses ]; then
		cd ${INSTALLPATH}/${USRLOCAL}/share/licenses
		for file in *
			do
				ln -Ffhs ${INSTALLPATH}/${USRLOCAL}/share/licenses/${file} ${USRLOCAL}/share/licenses/${file}
		done
	fi
}

postinit_cmd()
{
	# Check and generate temporary php script for postinit command.
	if ! grep -qw ${CWDIR}/${SCRIPTNAME} ${CONFIG}; then
		touch ${CWDIR}/postinit || error_notify "Error: A problem has occurred while creating the postinit file."
		chmod +x ${CWDIR}/postinit
		if [ ! "${PRDVERSION}" -ge "110" ]; then
			# Generate php script for NAS4Free 10.3 versions.
			cat << EOF > ${CWDIR}/postinit
<?php
require_once("config.inc");
require_once("functions.inc");
\$cmd = dirname(__FILE__)."/${SCRIPTNAME}";
	\$i =0;
	if ( is_array(\$config['rc']['postinit'] ) && is_array( \$config['rc']['postinit']['cmd'] ) ) {
		for (\$i; \$i < count(\$config['rc']['postinit']['cmd']);) {
			if (preg_match('/${SCRIPTNAME}/', \$config['rc']['postinit']['cmd'][\$i])) break; ++\$i; }
	}
	\$config['rc']['postinit']['cmd'][\$i] = \$config['cmd']."\$cmd";
	write_config();
?>
EOF
		else
			# Generate php script for NAS4Free/XigmaNAS 11.x versions.
			cat << EOF > ${CWDIR}/postinit
<?php
require_once("config.inc");
require_once("functions.inc");
\$cmd = dirname(__FILE__)."/${SCRIPTNAME}";
\$name = "Zrep Extension";
\$comment = "Start ${APPNAME}";
\$rc = &array_make_branch(\$config,'rc','param'); 
if(false === array_search_ex(\$name,\$rc,'name')):
	\$rc_param = [];
	\$rc_param['uuid'] = uuid();
	\$rc_param['name'] = \$name;
	\$rc_param['value'] = \$cmd;
	\$rc_param['comment'] = \$comment;
	\$rc_param['typeid'] = '2';
	\$rc_param['enable'] = true;
	\$rc[] = \$rc_param;
	write_config();
endif;
unset(\$rc);
?>
EOF
		fi

		# Execute temporary php script.
		if [ "${OBI_INSTALL}" != "ON" ]; then
			echo "Creating postinit command..."
			php-cgi -f ${CWDIR}/postinit && rm ${CWDIR}/postinit || \
			error_notify "Error: A problem has occurred while executing postinit file."
			echo "Done!"
		fi
		sysrc -f ${CWDIR}${ZREPCONF} GUI_ENABLE=YES INSTALL_DIR=${CWDIR} >/dev/null 2>&1
	fi
}

gui_start()
{
	# Initialize the extension gui.
	if [ -d "${CWDIR}/gui" ]; then
		# Always ensure the config directory/file exist.
		if [ ! -f "${CWDIR}${ZREPCONF}" ]; then
			# Try to restore default configuration.
			runtime_config
			# Set default config.
			sysrc -f ${CWDIR}${ZREPCONF} GUI_ENABLE=YES INSTALL_DIR=${CWDIR} >/dev/null 2>&1
		fi
		GUI_STATUS=$(sysrc -f ${CWDIR}${ZREPCONF} -qn GUI_ENABLE)
		if [ "${GUI_STATUS}" = "YES" ]; then
			# Store the installation path and link conf.
			if ! sysrc -f ${CWDIR}${ZREPCONF} -n INSTALL_DIR | grep -q "${CWDIR}"; then
				sysrc -f ${CWDIR}${ZREPCONF} INSTALL_DIR=${CWDIR} >/dev/null 2>&1
			fi
			mkdir -p ${ZREPCONFLINK}
			ln -Ffhs ${CWDIR}/conf ${ZREPCONFLINK}/conf
			# Copy the gui files.
			cp -R ${CWDIR}/gui/* ${WWWPATH}/ || error_notify "Error: A problem has occurred while copying extension gui files."
		fi
	fi
}

gui_enable()
{
	# Relink conf and copy the gui files.
	if [ -d "${CWDIR}/gui" ]; then
		mkdir -p ${ZREPCONFLINK}
		ln -Ffhs ${CWDIR}/conf ${ZREPCONFLINK}/conf
		sysrc -f ${CWDIR}${ZREPCONF} GUI_ENABLE=YES >/dev/null 2>&1
		cp -R ${CWDIR}/gui/* ${WWWPATH}/ || error_notify "Error: A problem has occurred while copying extension gui files."
		exit 0
	else
		error_notify "Error: Extension gui files not found."
	fi
}

gui_disable()
{
	# Disable gui if -t option specified.
	if [ -d "${CWDIR}/gui" ]; then
		rm -f ${WWWPATH}/zrep-gui.php
		rm -Rf ${WWWPATH}/ext/zrep-gui
		rm -f ${LOCALSHAREPATH}/locale-zrep
		rm -Rf ${ZREPCONFLINK}
		sysrc -f ${CWDIR}${ZREPCONF} GUI_ENABLE=NO >/dev/null 2>&1 || error_notify "Error: A problem while removing extension gui files."
		exit 0
	else
		error_notify "Error: Extension gui files not found."
	fi

	# Remove empty ext folder to prevent empty "Extensions" tab.
	if [ -d "${WWWPATH}/ext" ]; then
		if [ ! "$(ls -A ${WWWPATH}/ext)" ]; then
			rm -R ${WWWPATH}/ext
		fi
	fi
}

pkg_upgrade()
{
	# Re-fetch zrep package and extract.
	if [ -f "${CWDIR}/${FULLAPPNAME}/${ZREPPATH}/zrep" ]; then
		zrep_upgrade
	else
		zrep_initial_download
	fi

	# Check for extension updates.
	extension_upgrade
}

reset_install()
{
	# Reset the extension environment.
	echo "Removing extension files..."
	if [ -d ${CWDIR}/conf ]; then
		rm -rf ${CWDIR}/conf
	fi
	if [ -d ${CWDIR}/log ]; then
		rm -rf ${CWDIR}/log
	fi
	if [ -d ${CWDIR}/locale-zrep ]; then
		rm -rf ${CWDIR}/locale-zrep
	fi
	if [ -d ${CWDIR}/${FULLAPPNAME} ]; then
		rm -rf ${CWDIR}/${FULLAPPNAME}
	fi
	if [ -d ${CWDIR}/download ]; then
		rm -rf ${CWDIR}/download
	fi
	if [ -f ${CWDIR}/version ]; then
		rm -f ${CWDIR}/version
	fi
	runtime_config
}

remove_addon()
{
	# Confirm for addon removal.
	while :
		do
			read -p "Do you wish to proceed with the ${FULLAPPNAME} removal? [y/N]:" yn
			case ${yn} in
			[Yy]) break;;
			[Nn]) exit 0;;
			esac
		done
	echo "Proceeding..."
	
	if [ -d "${WWWPATH}/zrep-gui.php" ]; then
		rm -f ${WWWPATH}/zrep-gui.php
		rm -Rf ${WWWPATH}/ext/zrep-gui
		rm -f ${LOCALSHAREPATH}/locale-zrep
		rm -Rf ${ZREPCONFLINK}
	fi

	# Check for working platform.
	if [ "${PRDPLATFORM}" = "x64-embedded" ]; then
		if [ -d ${USRLOCAL}/share/examples/${KSH9X} ]; then
			rm -rf ${USRLOCAL}/share/examples/${KSH9X}
		fi
		if [ -f ${USRLOCAL}/man/man1/${KSH9X}.1.gz ]; then
			rm -f ${USRLOCAL}/man/man1/${KSH9X}.1.gz
		fi
		if [ -d ${USRLOCAL}/share/licenses/${KSH9X}-20120801_2 ]; then
			rm -rf ${USRLOCAL}/share/licenses/${KSH9X}-20120801_2
		fi
		if [ -f ${USRLOCAL}/bin/${KSH9X} ]; then
			rm -f ${USRLOCAL}/bin/${KSH9X}
		fi
		if [ -f ${USRLOCAL}/bin/${APPNAME} ]; then
			rm -f ${USRLOCAL}/bin/${APPNAME}
		fi
	elif [ "${PRDPLATFORM}" = "x64-full" ]; then
		if [ -f ${USRLOCAL}/bin/${APPNAME} ]; then
			rm -f ${USRLOCAL}/bin/${APPNAME}
		fi
		pkg delete -y ${KSH9X}
	fi

	# Remove addon related files and folders only-
	# to protect any user-created custom files.
	FILES="conf download gui locale-zrep log zrep-addon README.md postinit release_notes version zrep-init"
	for file in ${FILES}; do
		if [ -f ${CWDIR}/${file} ] || [ -d ${CWDIR}/${file} ]; then
			rm -rf ${CWDIR}/${file}
		fi
	done
	
	if [ ! -f ${USRLOCAL}/sbin/${SCRIPTNAME} ]; then
		rm ${USRLOCAL}/sbin/${SCRIPTNAME}
	fi

	echo "Done!"
	echo "Please manually remove the Zrep Extension Command Script from the WebGUI."
	exit 0
}

get_versions()
{
	# Get zrep-addon extension version.
	if [ -f "${CWDIR}/version" ]; then
		APPVERSION=$(cat ${CWDIR}/version)
	else
		APPVERSION="version file not found!"
	fi

	# Display product versions.
	echo -e "\nksh93 version:" && ${USRLOCAL}/bin/ksh93 --version
	echo -e "\nzrep version:" && ${USRLOCAL}/bin/zrep version
	echo -e "\nextension version:"
	echo "${FULLAPPNAME} ${APPVERSION}"
	exit 0
}

exec_status()
{
	# Log on startup success, else logging with faults.
	if [ $? -eq 0 ]; then
		MSG="script has been started successfully!"
		logger -t ${SCRIPTNAME} ${MSG}
	else
		MSG="script started with faults"
		logger -t ${SCRIPTNAME} ${MSG}
	fi
}

zrep_init()
{
	# Check for system compatibility.
	if [ ! "${PLATFORM}" = "amd64" ]; then
		echo "Unsupported platform!"; exit 1
	fi 
	# Check for product compatibility.
	if [ ! "${PRDVERSION}" -ge "110" ]; then
		echo "Unsupported version!"; exit 1
	fi

	echo "Initializing ${APPNAME}..."

	# Function calls.
	platform_check
	product_check
	exec_status
}

# Run-time configuration.
runtime_config

while getopts ":ouxrvgth" option; do
	case ${option} in
		[h]) echo "Usage: ${SCRIPTNAME} -[option]";
		echo "Options:"
		echo "        -u  Upgrade Zrep/Add-On packages."
		echo "        -v  Display product versions."
		echo "        -g  Enables the addon GUI."
		echo "        -t  Disable the addon GUI."
		echo "        -x  Reset ${FULLAPPNAME}."
		echo "        -r  Remove ${FULLAPPNAME}."
		echo "        -h  Display this help message."; exit 0;;
		[o]) OBI_INSTALL="ON";; # To prevent nested PHP-CGI call for installation with OBI.
		[u]) pkg_upgrade;;
		[x]) reset_install;;
		[r]) remove_addon;;
		[v]) get_versions;;
		[g]) gui_enable; exit 0 ;; # For enable the addon gui.
		[t]) gui_disable; exit 0 ;; # For disable the addon gui.
		[?]) echo "Invalid option, -h for usage."; exit 1;;
	esac
done
zrep_init
